---
- name: Install dependencies
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - python
    - curl
    - apt-transport-https
    - ca-certificates
    - apparmor

- name: add docker repository for Debian
  shell: add-apt-repository "deb https://apt.dockerproject.org/repo/ debian-$(lsb_release -cs) main"
  when: ansible_distribution == "Debian"

- name: add docker repository for Ubuntu
  shell: add-apt-repository "deb https://apt.dockerproject.org/repo/ ubuntu-$(lsb_release -cs) main"
  when: ansible_distribution == "Ubuntu"

- name: add key id
  apt_key:
    url: "https://yum.dockerproject.org/gpg"
    state: present

- name: install docker
  apt:
    name: docker-engine
    update_cache: yes
    state: present

- name: install pip
  shell: curl -sSL https://bootstrap.pypa.io/get-pip.py | python

- name: install docker-py and docker-compose
  pip:
    name: docker-py
  with_items:
    - docker-py
    - docker-compose
